# Generated by Django 3.2.5 on 2021-08-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
